// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq72yS9fAEk_tuBR6sTS6uhoq5TOB6Qr4',
    appId: '1:618187123184:web:4a8efbf845e3a39a3d9535',
    messagingSenderId: '618187123184',
    projectId: 'garzon-5d8a3',
    authDomain: 'garzon-5d8a3.firebaseapp.com',
    storageBucket: 'garzon-5d8a3.firebasestorage.app',
    measurementId: 'G-PZ5T9VGST2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXC20Kki4t1WsbcqEgTHtUDpTsuxTzgyA',
    appId: '1:618187123184:android:fb82d666f46a02823d9535',
    messagingSenderId: '618187123184',
    projectId: 'garzon-5d8a3',
    storageBucket: 'garzon-5d8a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcykCsWhi2Jh-iuMQLyOWfANvC1eiExL8',
    appId: '1:618187123184:ios:cdb9c720dd93e1963d9535',
    messagingSenderId: '618187123184',
    projectId: 'garzon-5d8a3',
    storageBucket: 'garzon-5d8a3.firebasestorage.app',
    iosBundleId: 'com.example.controlMultasSalon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcykCsWhi2Jh-iuMQLyOWfANvC1eiExL8',
    appId: '1:618187123184:ios:cdb9c720dd93e1963d9535',
    messagingSenderId: '618187123184',
    projectId: 'garzon-5d8a3',
    storageBucket: 'garzon-5d8a3.firebasestorage.app',
    iosBundleId: 'com.example.controlMultasSalon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq72yS9fAEk_tuBR6sTS6uhoq5TOB6Qr4',
    appId: '1:618187123184:web:8baf5ad72215e7073d9535',
    messagingSenderId: '618187123184',
    projectId: 'garzon-5d8a3',
    authDomain: 'garzon-5d8a3.firebaseapp.com',
    storageBucket: 'garzon-5d8a3.firebasestorage.app',
    measurementId: 'G-22B5X49RG0',
  );
}
